main/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
        path('login/', views.login_index, name='LoginUrl'),
        path('logout/', views.logout_index, name='LogoutUrl'),
        path('join/', views.join_index, name='JoinUrl'),
        path('update/', views.update_index, name='UpdateUrl'),
         path('mypage/', views.mypage_view, name='MyPageUrl'),
        path('delete/', views.delete_index, name='DeleteUrl'),
        path('search', views.search_index, name="SearchUrl"),
]

mighty7/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('', views.index, name="index"),
    path('search', views.search_index, name="SearchUrl"),
    path('location', views.location_index, name="LocationUrl"),
    path('map', views.map_index, name="MapUrl"),
    path('admin/', admin.site.urls),
    path('users/', include('main.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    
    class Meta:
        db_table = 'user'

class Stay(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, db_column='user_id')
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lon = models.DecimalField(max_digits=9, decimal_places=6)
    
    @classmethod
    def create(cls, id, lat, lng):
        stay = cls(user_id=id, lat=lat, lon=lng)
        stay.save()
    
    class Meta:
        db_table = 'stay'
    
class Category(models.Model):
    category = models.CharField(max_length=2, primary_key=True)
    
    class Meta:
        db_table = 'category'

class Place(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default="명소", unique=False, db_column='category')
    name = models.CharField(max_length=50)
    location = models.TextField()
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lon = models.DecimalField(max_digits=9, decimal_places=6)
    
    class Meta:
        db_table = 'place'

class Search(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, unique=False, db_column='user_id')
    pl_id = models.ForeignKey(Place, on_delete=models.CASCADE, unique=False, db_column='pl_id')
    
    @classmethod
    def create(cls, user_id, pl_id):
        search = cls(user_id=user_id, pl_id=pl_id)
        search.save()
        
    class Meta:
        db_table = 'search'

main/views.py
from django.shortcuts import render, redirect
from .models import User, Place, Stay, Search
from .modules import map
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from django.db.models import Q
import folium
import osmnx as ox
import networkx as nx
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

def index(request):
    places = Place.objects.filter(category = '명소').order_by('?')[:5]
    cafes = Place.objects.filter(category = '카페').order_by('?')[:5]
    restaurants = Place.objects.filter(category = '식당').order_by('?')[:5]
    
    return render(request, 'main/index.html', {'places' : places,
                                            'cafes' : cafes,
                                            'restaurants' : restaurants,})

def login_index(request):
    if request.method == 'POST':
        account = request.POST.get('account')

        if account == 'login':
            username = request.POST.get('username')
            password = request.POST.get('password')

            userObject = authenticate(request, username=username, password=password)

            if userObject is not None:
                login(request, userObject)
                return redirect('/')  # 로그인 성공 시 메인 페이지로 리다이렉트
            else:
                # 로그인 실패 시 오류 메시지를 전달하고 다시 로그인 페이지를 렌더링
                return render(request, 'user/login.html', {'error_msg': '아이디 또는 비밀번호가 올바르지 않습니다.'})

        else:
            # 회원가입 페이지로 리다이렉트
            return redirect('users:JoinUrl')

    # GET 요청인 경우 로그인 페이지를 렌더링
    return render(request, 'user/login.html', {})

def logout_index(request):
    logout(request)
    return redirect('users:LoginUrl')

def join_index(request):
    if request.method == 'POST':
        account = request.POST.get('account')
        print(account)

        if account == 'create':
            new_username = request.POST.get('username')
            new_password = request.POST.get('password')
            new_password_check = request.POST.get('password_check')
            print(new_username)
            print(new_password)

            if not new_username or not new_password:
                return render(request, 'user/join.html', {'error_msg' : '아이디 또는 비밀번호를 입력하세요.'})
            
            elif new_password != new_password_check:
                return render(request, 'user/join.html', {'error_msg':'비밀번호가 서로 같지 않습니다.'})
            
            elif User.objects.filter(username=new_username).exists():
                return render(request, 'user/join.html', {'error_msg':'이미 사용중인 아이디입니다.'})
            
            # 새로운 사용자 생성
            User.objects.create_user(username=new_username, password=new_password)

            return redirect('users:LoginUrl')  # 회원가입 완료 후 로그인 페이지로 리다이렉트
        
        else:
            # account가 'create'가 아닐 경우 처리
            return render(request, 'user/join.html', {'error_msg': '잘못된 요청입니다.'})

    # GET 요청일 때 회원가입 페이지 렌더링
    return render(request, 'user/join.html', {})

def update_index(request):
    if request.method == 'POST':
        account = request.POST.get('account')

        if account == 'update':
            # 현재 로그인된 사용자
            current_user = request.user
            password = request.POST.get('password')

            # 비밀번호 확인
            if current_user.check_password(password):
                new_username = request.POST.get('new_username')
                new_password = request.POST.get('new_password')
                new_password_confirm = request.POST.get('new_password_confirm')

                # 새 비밀번호와 확인 비밀번호가 일치하는지 확인
                if new_password == new_password_confirm:
                    # 아이디 업데이트
                    current_user.username = new_username if new_username else current_user.username
                    # 비밀번호 업데이트
                    if new_password:  # 새로운 비밀번호가 입력된 경우만 업데이트
                        current_user.set_password(new_password)

                    current_user.save()  # 변경 사항 저장

                    # 사용자 로그아웃 처리
                    logout(request)

                    # 로그아웃 후 로그인 페이지로 리다이렉트
                    return redirect('users:LoginUrl')
                else:
                    return render(request, 'user/update.html', {'error_msg': '새 비밀번호가 일치하지 않습니다.'})
            else:
                return render(request, 'user/update.html', {'error_msg': '현재 비밀번호가 올바르지 않습니다.'})
        else:
            return redirect('users:LoginUrl')
    else:
        return render(request, 'user/update.html')

def delete_index(request):
    if request.user.is_authenticated:
        user = request.user
        logout(request)  # 로그아웃 처리
        user.delete()    # 사용자 계정 삭제
        return redirect('index')  # 메인 페이지로 리다이렉트

def search_index(request):
    if request.method == 'GET':
        try:
            user = request.user
            search_list = Search.objects.filter(user_id = user).values("pl_id_id")
            search_places = Place.objects.filter(id__in = search_list)
            
            return render(request, 'main/search.html', {'search_places' : search_places,
                                                        'name' : user.username})
        except:
            return render(request, 'main/search.html')
    
    elif request.method == 'POST':
        
        search = request.POST.get('search')
        search_category = request.POST.get('search_category')
        
        search_text = request.POST.get('search_text')
        
        try:
            user = request.user
            search_list = Search.objects.filter(user_id = user).values("pl_id_id")
            search_places = Place.objects.filter(id__in = search_list)
            
            if not search_text.strip():
                return render(request, 'main/search.html', {'error_msg':'검색어를 입력하세요.',
                                               'search_places' : search_places,
                                               'name' : user.username})
                    
            if search == 'search' and search_category == 'None':
                q_filter = Q()
                for field in ["name", "location"]:
                    q_filter |= Q(**{f"{field}__icontains": search_text})
                    
                places = Place.objects.filter(q_filter, category = '명소')
                cafes = Place.objects.filter(q_filter, category = '카페')
                restaurants = Place.objects.filter(q_filter, category = '식당')
                
                return render(request, 'main/search.html', {'places' : places,
                                                            'cafes' : cafes,
                                                            'restaurants' : restaurants,
                                               'search_places' : search_places,
                                               'name' : user.username})
            
            elif search == 'search' and search_category == 'Name':
                    
                places = Place.objects.filter(name__contains = search_text, category = '명소')
                cafes = Place.objects.filter(name__contains = search_text, category = '카페')
                restaurants = Place.objects.filter(name__contains = search_text, category = '식당')
                
                return render(request, 'main/search.html', {'places' : places,
                                                            'cafes' : cafes,
                                                            'restaurants' : restaurants,
                                               'search_places' : search_places,
                                               'name' : user.username})
            
            elif search == 'search' and search_category == 'Location':
                    
                places = Place.objects.filter(location__contains = search_text, category = '명소')
                cafes = Place.objects.filter(location__contains = search_text, category = '카페')
                restaurants = Place.objects.filter(location__contains = search_text, category = '식당')
                
                return render(request, 'main/search.html', {'places' : places,
                                                            'cafes' : cafes,
                                                            'restaurants' : restaurants,
                                               'search_places' : search_places,
                                               'name' : user.username})
            
            return render(request, 'main/search.html', {'error_msg':'검색이 올바르지 않습니다.',
                                               'search_places' : search_places,
                                               'name' : user.username})
        except:
            if not search_text.strip():
                return render(request, 'main/search.html', {'error_msg':'검색어를 입력하세요.'})
                    
            if search == 'search' and search_category == 'None':
                q_filter = Q()
                for field in ["name", "location"]:
                    q_filter |= Q(**{f"{field}__icontains": search_text})
                    
                places = Place.objects.filter(q_filter, category = '명소')
                cafes = Place.objects.filter(q_filter, category = '카페')
                restaurants = Place.objects.filter(q_filter, category = '식당')
                
                return render(request, 'main/search.html', {'places' : places,
                                                            'cafes' : cafes,
                                                            'restaurants' : restaurants})
            
            elif search == 'search' and search_category == 'Name':
                    
                places = Place.objects.filter(name__contains = search_text, category = '명소')

main/templates/user/join.html
<!DOCTYPE html>
<html lang="ko">
<head>
    {% load static %}
    <!-- 부트스트랩 및 커스텀 CSS 추가 -->
    {% load django_bootstrap5 %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- CSS 파일 로드 -->
    <link rel="stylesheet" href="{% static 'css/join.css' %}">


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>
<body>
    <div class="container">
        <form action="{% url 'users:JoinUrl' %}" method="post">
            {% csrf_token %}

            <!-- 상단 링크 -->
            
            <!-- <div class="link-container">
                <button class="link-button" onclick="window.location.href='{% url 'users:LoginUrl' %}'">로그인</button>
                <button class="link-button" onclick="window.location.href='{% url 'index' %}'">메인</button>
            </div> -->
            

            <h1>회원 정보 입력</h1>
            <p>새로운 아이디와 비밀번호를 입력하세요.</p>

            {% if error_msg %}
            <div class="error_msg">
                {{ error_msg }}
            </div>
            {% endif %}

            <!-- 입력 폼 -->
            <input type="text" name="username" placeholder="아이디" required>
            <input type="password" name="password" placeholder="비밀번호" required>
            <input type="password" name="password_check" placeholder="비밀번호 확인" required>

            <!-- 버튼들 -->
            <button type="submit" value="create" name="account">회원가입</button>
            
            <div class="link_container">
                <a href="{% url 'users:LoginUrl' %}" class="link_style">로그인</a>
                <a href="{% url 'index' %}" class="link_style">메인</a>
             
            </div>

            
        </form>
    </div>
</body>
</html>

main/templates/user/login.html
<!DOCTYPE html>
<html lang="ko">
<head>

    {% load static %}
    <!-- 부트스트랩 및 커스텀 CSS 추가 -->
    {% load django_bootstrap5 %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS 파일 로드 -->
    <link rel="stylesheet" href="{% static 'css/loginpage.css' %}">

    <title>로그인</title>
    
    <script>
        const signUpButton = document.getElementById('signUp');
        const signInButton = document.getElementById('signIn');
        const container = document.getElementById('container');

        signUpButton.addEventListener('click', () => {
	        container.classList.add("right-panel-active");
        });

        signInButton.addEventListener('click', () => {
	        container.classList.remove("right-panel-active");
        });

        function closeErrorMessage() {
            var errorMessageDiv = document.getElementById('error-message');
            errorMessageDiv.style.display = 'none';  // 오류 메시지를 숨김
        }

        function redirectToJoinPage() {
            window.location.href = "http://127.0.0.1:8000/users/join/";
        }
    </script>
</head>
<body>

    <!-- 오류 메시지를 페이지 상단에 표시 -->
    {% if error_msg %}
        <div id="error-message" class="error-message">
            {{ error_msg }}
            <br>
            <button class="close-btn" onclick="closeErrorMessage()">확인</button>
        </div>
    {% endif %}

    <div class="container" id="container">
        <div class="form-container sign-up-container">
			
			<!-- <h2><a href="{% url 'users:LoginUrl' %}">로그인</a></h2> -->
            <form action="#" method="post">
                <h1>Create Account</h1>
                <div class="social-container">
                    <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>or use your email for registration</span>
                <input type="text" placeholder="Name" />
                <input type="email" placeholder="Email" />
                <input type="password" placeholder="Password" />
                <button>Sign Up</button>
            </form>
        </div>

        <div class="form-container sign-in-container">
            <!-- 로그인 폼 -->
            <form action="{% url 'users:LoginUrl' %}" method="post">
                {% csrf_token %}
				<h6><a href="{% url 'index' %}" class="main-page-link">메인</a></h6>
                <h5>로그인</h5>
                <div><input name="username" type="text" placeholder="아이디"></div>
                <div class="inputbox"><input name="password" type="password" placeholder="비밀번호"></div>
                <div><button type="submit" name="account" value="login" class="btn btn-primary">로그인</button></div>
            </form>
        </div>

        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>To keep connected with us please login with your personal info</p>
                    <button class="ghost" id="signIn">로그인</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>환영합니다!</h1>
                    <p>회원가입을 하고 <br/>당신의 여정을 시작하세요</p>
                    <button id="signUp" onclick="redirectToJoinPage()">Sign Up</button>
                </div>
            </div>
        </div>
    </div>
    <!-- 커스텀 JS 추가 -->
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/loginpage.js' %}"></script>

</body>
</html>

main/templates/user/mypage.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>마이 페이지</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}">
</head>
<body>
    <div class="container">
       
        <header class="header">
            <h1>마이 페이지</h1>
            <a href="{% url 'index' %}" class="main-page-link">
                <button type="button">메인으로 돌아가기</button>
            </a>
        </header>

        <section class="profile-section">
            <h2>{{ user.username }}님의 회원정보</h2>
            <p>이메일: {{ user.email }}</p>
            <p>가입일: {{ user.date_joined }}</p>
        </section>

        <section class="action-buttons">
            <a href="{% url 'users:LogoutUrl' %}" class="profile-button">
                <button type="button">로그아웃</button>
            </a>
            <a href="{% url 'users:UpdateUrl' %}" class="profile-button">
                <button type="button">아이디/비밀번호 변경</button>
            </a>

            <a href="{% url 'users:DeleteUrl' %}" class="profile-button">
    <button type="button" onclick="return confirm('정말로 계정을 삭제하시겠습니까?')">회원 삭제</button>
</a>
        </section>

        <div class="greeting-section">
            <p>안녕하세요, {{ user.username }}님!</p>
            <p>아이디 및 비밀번호를 여기서 변경할 수 있습니다.</p>
        </div>
    </div>
</body>
</html>

main/templates/user/update.html
<!DOCTYPE html>
<html lang="ko">
<head>
    {% load static %}
    <!-- 부트스트랩 및 커스텀 CSS 추가 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원 정보 수정</title>
</head>
<body>
    <h6><a href="{% url 'index' %}" class="main-pages">메인</a></h6>
    <div class="container">
     

        <h1>회원 정보 수정 페이지</h1>
        <br>
        <div>회원 정보 수정</div>
        <br>  

        {% if user.is_authenticated %}
            <div>{{ user.username }} 님으로 로그인 중</div>
            <form action="{% url 'users:UpdateUrl' %}" method="post">
                {% csrf_token %}
                {% if error_msg %}
                    <div class="error">{{ error_msg }}</div>
                {% endif %}
                
                <div class="form-group">
                    기존 아이디 : <input name="username" type="text" class="form-control" value="{{ user.username }}" disabled>
                </div>
                
                <div class="form-group">
                    새로운 아이디 : <input name="new_username" type="text" class="form-control" placeholder="새로운 아이디를 입력하세요">
                </div>
                
                <div class="form-group">
                    기존 비밀번호 : <input name="password" type="password" class="form-control" placeholder="기존 비밀번호를 입력하세요">
                </div>
                
                <div class="form-group">
                    새로운 비밀번호 : <input name="new_password" type="password" class="form-control" placeholder="새로운 비밀번호를 입력하세요">
                </div>
                
                <div class="form-group">
                    비밀번호 확인 : <input name="new_password_confirm" type="password" class="form-control" placeholder="비밀번호를 다시 입력하세요">
                </div>
                
                <button type="submit" name="account" value="update" class="btn btn-primary btn-block">정보 수정</button>
            </form>

        
        {% endif %}
    </div>
</body>
</html>